---

require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  DisplayCopNames: true
  SuggestExtensions: false
  Exclude:
    - 'bin/**'
    - 'db/schema.rb'
    - 'db/migrate/**'
    - 'db/seeds.rb'

Style/Documentation:
  Enabled: false
Naming/VariableNumber:
  CheckSymbols: false
RSpec/NestedGroups:
  Max: 5
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/MultipleExpectations:
  Max: 7
RSpec/ExampleLength:
  Max: 10
RSpec/ContextWording:
  Include:
    - cheks for